[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pi3"
version = "0.1"
description = "pi3"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "huggingface-hub",
    "numpy==1.26.4",
    "opencv-python",
    "pillow",
    "plyfile",
    "safetensors",
    "torch==2.7.1",
    "torchvision==0.22.1",
    "tqdm",
]

[project.optional-dependencies]
demo = [
    "gradio",
    "matplotlib",
    "scipy",
    "trimesh",
]

[tool.setuptools.packages.find]
include = ["pi3", "pi3.*"]

[tool.uv]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.setuptools.package-data]
"pi3" = ["**/*"]
